# 카이제곱 교차검증
- 두 범주형 변수가 서로 독립적인지 검정

In [1]:
import pandas as pd

## 데이터 로딩

In [35]:
df = pd.read_csv("datas2/성별에따른만족도.csv", encoding = 'euc-kr')
df.head()

만족도  성별
0  불만족  남성
1   보통  여성
2  불만족  여성
3   보통  남성
4   만족  여성

## 실제값 교차 테이블 생성

In [36]:
cross_table = pd.crosstab(df['성별'], df['만족도'])

In [37]:
cross_table

만족도  만족  보통  불만족
성별              
남성   50  40   10
여성   40  30   30

## obs 데이터 추출

In [23]:
# 크로스테이블의 값만 추출함 -> numpy 객체
# observed
obs = cross_table.values
obs

array([[50, 40, 10],
       [40, 30, 30]])

In [26]:
from scipy import stats as st
statistic, pvalue, dof, expected_freq = st.chi2_contingency(obs)

In [30]:
results = st.chi2_contingency(obs)
results.expected_freq

array([[45., 35., 20.],
       [45., 35., 20.]])

## 기대값 확인
- 데이터 프레임으로 만들기

In [38]:
cross_table.head()

만족도  만족  보통  불만족
성별              
남성   50  40   10
여성   40  30   30

In [41]:
expected_freq

array([[45., 35., 20.],
       [45., 35., 20.]])

In [43]:
expected_df = pd.DataFrame(expected_freq, index=cross_table.index, columns=cross_table.columns)
expected_df

만족도    만족    보통   불만족
성별                   
남성   45.0  35.0  20.0
여성   45.0  35.0  20.0